#!/usr/bin/env python3
"""Generate the witness envelopes from the real public API."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from green_line import (
    CultivationAttempt,
    Observation,
    canonical_envelope,
    read_cultivation,
    reading_envelope,
)

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "envelopes"
OUT.mkdir(parents=True, exist_ok=True)

# Worked example: an honest small scenario - a learner practising proof review
# with a mentor, two markers declared, review pinned to a stated date.
WORKED_ATTEMPT = CultivationAttempt(
    description=(
        "Practising formal proof review under a named mentor, with session logs kept"
    ),
    tags=frozenset({"research", "teaching"}),
    dated_observations=(
        Observation("mentor", "2026-08-15"),
        Observation("session_log", "2026-08-20"),
    ),
)
WORKED_AS_OF = "2026-08-29"
WORKED_REFS = (
    "generated by scripts/gen_envelopes.py in this repository (green_line 0.1.0)",
    "scenario: docs/manuscript/04_examples.md worked read",
)

reading = read_cultivation(WORKED_ATTEMPT, as_of=WORKED_AS_OF)
envelope = reading_envelope(
    reading,
    subject_id="green_line worked read: the proof-review apprenticeship attempt (docs/manuscript/04_examples.md)",
    source_snapshot_refs=WORKED_REFS,
)
(OUT / "green_line_worked.json").write_text(canonical_envelope(envelope) + "\n", encoding="utf-8")
print("worked native_status:", reading.status.value)

# Same-subject scenario: the declared subject is witness_register 0.1.0 itself,
# matching what the four existing same_subject envelopes address. The
# declarations below are the registrar's honest reading of what a growth
# instrument can honestly declare about that release: the reviewer-facing
# handoff and limits work is still growing; nothing here claims mastery.
SUBJECT_ID = (
    "witness_register 0.1.0 (docxology/witness_register, commits 56962fe + 49ebea4, "
    "2026-07-29); registrar: the operator's assistant, filing growth observations "
    "from the repository's own records"
)
SUBJECT_REFS = (
    "mentor: docs/correspondence.md records the answered external review",
    "session_log: CHANGELOG.md hardening entries, 2026-07-29",
    "gap_list: docs/manuscript/03_limits.md names what is still unresolved",
    "review_note: docs/correspondence.md review attribution",
    "uncertainty: docs/manuscript/03_limits.md beside every claim",
)
SAME_SUBJECT_ATTEMPT = CultivationAttempt(
    description=(
        "witness_register 0.1.0 as a growing instrument: review practices, "
        "recorded limits, and the handoff habits that are still being learned"
    ),
    tags=frozenset({"research", "teaching", "writing"}),
    dated_observations=(
        Observation("mentor", "2026-07-29"),
        Observation("session_log", "2026-07-29"),
        Observation("review_note", "2026-07-29"),
        Observation("uncertainty", "2026-07-29"),
    ),
)

ss_reading = read_cultivation(SAME_ATTEMPT := SUBJECT_REFS and CultivationAttempt(
    description=SUBJECT_REFS and (
        "witness_register 0.1.0 as a growing instrument: review practices, "
        "recorded limits, and handoff habits still under development"
    ),
    tags=frozenset({"research", "teaching", "writing"}),
    dated_observations=(
        Observation("mentor", "2026-07-29"),
        Observation("session_log", "2026-07-29"),
        Observation("review_note", "2026-07-29"),
        Observation("uncertainty", "2026-07-29"),
    ),
), as_of="2026-07-29")
ss_envelope = reading_envelope(
    ss_reading,
    subject_id=SUBJECT_ID,
    source_snapshot_refs=SUBJECT_REFS,
)
(OUT / "green_line_same_subject.json").write_text(
    canonical_envelope(ss_envelope) + "\n", encoding="utf-8"
)
print("same_subject native_status:", ss_reading.status.value)
